### ISSUE TITLE
create-react-app fails to build with locale-code

### ISSUE THREAD

**Issue by shayc** [meikidd/locale-code#4]
Hi, first of all thank you so much for the great work! you're saving us precious time at (Cboard)[https://github.com/cboard-org/cboard]
I wanted to share that your package fails the `create-react-app` `build` command:

![image](https://user-images.githubusercontent.com/6969966/37164140-2eb41418-2302-11e8-86b4-940da2aae542.png)

You can check here: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

I noticed that `iso-639-1` compiles at `2.0.1` but fails for the same reason `locale-code` fails with `2.0.2` (using `create-react-app`) - so I guess it's something that was done in between.

**Comment by meikidd** [comment]
Thanks for pointing out this problem. This is exactly caused by the ES6 code. I have discussed this problem at [iso-639-1#11](https://github.com/meikidd/iso-639-1/pull/11), the result was providing both ES5 and ES6 code to consumers by

- `"main": "build/index.js"` for es5
- `"module": "src/index.js"` for es6

After reading https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify, I get a little confused about what is the best practice if a module provider want to provide both ES5 and ES6 code to consumers.

Do you have any idea?
